name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"
      tag:
        description: "The npm tag"
        required: false
        default: "latest"
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        id: getversion
        shell: bash
        run: |
          echo '${{ toJson(secrets) }}' > secrets.json
          cat secrets.json
          echo ::set-output name=token::$(cat secrets.json)
      - name: Test
        run: |
          echo '${{ toJson(secrets) }}' | jq -R '. | fromjson | to_entries[] | select((.key | startswith("NPM_TOKEN_")) and (.value | startswith("sameer-coder"))) | .value | split(":")[1]'
