name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"
      tag:
        description: "The npm tag"
        required: false
        default: "latest"
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          USER_NPM_TOKEN=$(jq --arg v "{{secrets}}" '$v | to_entries[] | select((.key | startswith("npm_token_")) and (.value | startswith("sameer-coder"))) | .value | split(":")[1]')
      - uses: sameer-coder/optic-release-automation-action@multiple-tokens # you can use a tag instead of main
        with:
          user-npm-token: $USER_NPM_TOKEN
          github-token: ${{secrets.github_token}}
          npm-token: ${{secrets.NPM_TOKEN}}
          optic-token: ${{secrets.OPTIC_TOKEN}}
          semver: ${{ github.event.inputs.semver }}
          npm-tag: ${{ github.event.inputs.tag }}
          optic-url: http://0278-1-186-117-193.ngrok.io/api/generate/
          api-url: https://optic-release-automation-ocrlhra4va-ue.a.run.app/
