name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"
      tag:
        description: "The npm tag"
        required: false
        default: "latest"
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        id: getversion
        shell: bash
        run: |
          echo "::set-output name=token::$(echo ${{ secrets }})"
      - name: Test
        run: |
          echo "$(jq -R '.' <<< ${{ steps.getversion.outputs.token }})"
