name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"
      tag:
        description: "The npm tag"
        required: false
        default: "latest"
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        shell: bash
        run: |
          echo "${{ toJson(secrets) }}" > secrets.json
          echo "USER_NPM_TOKEN=$(cat secrets.json | jq 'to_entries|map("\(.key)=\(.value|tostring)")|.[]')"
      - name: Test
        run: echo $USER_NPM_TOKEN
