name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"
      tag:
        description: "The npm tag"
        required: false
        default: "latest"
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        id: getversion
        shell: bash
        run: |
          echo '${{ toJson(secrets) }}' > secrets.json
          cat secrets.json
          echo ::set-output name=tokens::$(cat secrets.json)
      - name: Test
        run: |
          USER_NPM_TOKEN=$(echo '${{ steps.getversion.outputs.tokens }}' | jq -R '. | fromjson | to_entries[] | select((.key | startswith("NPM_TOKEN_")) and (.value | startswith("${{github.actor}}"))) | .value | split(":")[1]')
          USER_OPTIC_TOKEN=$(echo '${{ steps.getversion.outputs.tokens }}' | jq -R '. | fromjson | to_entries[] | select((.key | startswith("OPTIC_TOKEN_")) and (.value | startswith("${{github.actor}}"))) | .value | split(":")[1]')
          echo $USER_NPM_TOKEN
          echo $USER_OPTIC_TOKEN
        continue-on-error: true
