name: token

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"
      tag:
        description: "The npm tag"
        required: false
        default: "latest"
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      username: ${{ github.actor }}
    steps:
      - uses: sameer-coder/optic-release-automation-action@test-multiple # you can use a tag instead of main
        with:
          user-npm-token: ${{ secrets[format('NPM_TOKEN_{0}', env.username)] }}
          user-optic-token: ${{ secrets[format('OPTIC_TOKEN_{0}', env.username)] }}
          github-token: ${{secrets.github_token}}
          npm-token: ${{secrets.NPM_TOKEN}}
          optic-token: ${{secrets.OPTIC_TOKEN}}
          semver: ${{ github.event.inputs.semver }}
          npm-tag: ${{ github.event.inputs.tag }}
          optic-url: http://0278-1-186-117-193.ngrok.io/api/generate/
          api-url: https://optic-release-automation-ocrlhra4va-ue.a.run.app/
