{
  "status": 201,
  "url": "https://api.github.com/repos/sameer-coder/safe-stable-stringify/releases",
  "headers":
    {
      "access-control-allow-origin": "*",
      "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
      "cache-control": "private, max-age=60, s-maxage=60",
      "connection": "close",
      "content-length": "1980",
      "content-security-policy": "default-src 'none'",
      "content-type": "application/json; charset=utf-8",
      "date": "Fri, 03 Dec 2021 12:21:23 GMT",
      "etag": '"bf071d463f3d5fe84092e2a509d1ff7f56e9a90d21bb65d7d1c5ae2aafc1e1f8"',
      "location": "https://api.github.com/repos/sameer-coder/safe-stable-stringify/releases/54573422",
      "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
      "server": "GitHub.com",
      "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
      "vary": "Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With",
      "x-content-type-options": "nosniff",
      "x-frame-options": "deny",
      "x-github-media-type": "github.v3; format=json",
      "x-github-request-id": "F2E1:5A5C:1AB74F:86AF5B:61AA0BC3",
      "x-ratelimit-limit": "5000",
      "x-ratelimit-remaining": "4999",
      "x-ratelimit-reset": "1638537683",
      "x-ratelimit-resource": "core",
      "x-ratelimit-used": "1",
      "x-xss-protection": "0",
    },
  "data":
    {
      "url": "https://api.github.com/repos/sameer-coder/safe-stable-stringify/releases/54573422",
      "assets_url": "https://api.github.com/repos/sameer-coder/safe-stable-stringify/releases/54573422/assets",
      "upload_url": "https://uploads.github.com/repos/sameer-coder/safe-stable-stringify/releases/54573422/assets{?name,label}",
      "html_url": "https://github.com/sameer-coder/safe-stable-stringify/releases/tag/untagged-0204885f72cc30bf4dab",
      "id": 54573422,
      "author":
        {
          "login": "optic-release-automation[bot]",
          "id": 94357573,
          "node_id": "BOT_kgDOBZ_IRQ",
          "avatar_url": "https://avatars.githubusercontent.com/u/1544687?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/optic-release-automation%5Bbot%5D",
          "html_url": "https://github.com/apps/optic-release-automation",
          "followers_url": "https://api.github.com/users/optic-release-automation%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/optic-release-automation%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/optic-release-automation%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/optic-release-automation%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/optic-release-automation%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/optic-release-automation%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/optic-release-automation%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/optic-release-automation%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/optic-release-automation%5Bbot%5D/received_events",
          "type": "Bot",
          "site_admin": false,
        },
      "node_id": "RE_kwDOGeGFSc4DQLlu",
      "tag_name": "v2.3.1",
      "target_commitish": "main",
      "name": "v2.3.1",
      "draft": true,
      "prerelease": false,
      "created_at": "2021-12-03T12:21:23Z",
      "published_at": null,
      "assets": [],
      "tarball_url": null,
      "zipball_url": null,
      "body": "**Full Changelog**: https://github.com/sameer-coder/safe-stable-stringify/compare/v2.3.0...v2.3.1",
    },
}
